spring:
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
  datasource:
    url: jdbc:postgresql://localhost:5432/edustor_upload
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
