server:
  port: 8083
spring:
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
  datasource:
      url: jdbc:postgresql://postgres.edustor.svc.cluster.local:5432/edustor_upload
      username: postgres
  jpa:
      hibernate:
        ddl-auto: update
      generate-ddl: true
